### PR TITLE
commit:added link

### PR DESCRIPTION
**Pull request by NrusinghaMohanty**

### CODE REVIEW

**Comment by NrusinghaMohanty** [comment]
https://github.com/NrusinghaMohanty/CSS_Wizardry_Component_Library/pull/1

**Comment by NrusinghaMohanty** [comment]
link:  https://css-wizardry.netlify.app/

**Comment by shashankorthiwada** [comment]
You can use scroll-behavior: smooth; and Change the Font Style.. Rest Everything is Fine.

**Comment by shubambhasin** [comment]
### Points where it cam be improved
* You can make use of variables for colors so that ever in future you can modify them with minimum refactoring
* in docs website, there is some issues with the buttons when we click on them it takes us to the top of the page
* scroll behaviour smooth can be added for smooth transitions.
* You can also structure your files in separate folders. 

Rest is fine, nice work 😄😄

**Pull request merged**
